version: "3"
services:
    # PHP with Nginx
    admin-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: admin-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "9999:9999"
        networks:
            - real_estate_admin_network

    admin-nginx:
        image: nginx:alpine
        container_name: admin-nginx
        restart: unless-stopped
        ports:
            - "8888:8888"
        volumes:
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - admin-app
            - admin-db
        networks:
            - real_estate_admin_network

    admin-db:
        image: mariadb:10.5
        container_name: admin-db
        volumes:
            - "./data:/var/lib/mysql"
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_ROOT_USER=root
        networks:
            - real_estate_admin_network
        restart: unless-stopped

networks:
    real_estate_admin_network:
        driver: bridge
